In [1]:
import numpy as np

## np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty = np.empty(shape=(2,3))

In [3]:
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
array_0s=np.zeros(shape=(2,3))
array_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_0s=np.zeros(shape=(2,3), dtype=np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [7]:
array_1s=np.ones(shape=(2,3))
array_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array_full=np.full(shape=(2,3), fill_value=2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

## "_like" functions

In [9]:
matrix_A=np.array([[1,0,9,2,2],[3,23,4,5,1],[0,2,3,4,1]])
matrix_A

array([[ 1,  0,  9,  2,  2],
       [ 3, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [10]:
array_empty_like=np.empty_like(matrix_A)
array_empty_like

array([[                  0,                   0, 4607182418800017408,
        4589168020290535424, 4598175219545276416],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4617385886705778688],
       [4612248968380809216, 4607182418800017408, 4625196817309499392,
        4616189618054758400, 4607182418800017408]])

In [11]:
array_0s_like=np.zeros_like(matrix_A)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])