In [1]:
import numpy as np

## Indexing

In [2]:
array_a=np.array([[1,2,3],[4,5,6]])

In [3]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Specific values

In [4]:
array_a[1]

array([4, 5, 6])

In [5]:
array_a[0][1]

2

In [6]:
array_a[1][0]

4

In [7]:
array_a[1,0]

4

In [8]:
array_a[:,0]

array([1, 4])

## Negative indices

In [9]:
array_b=np.array([1,2,3])

In [10]:
array_b[-1]

3

In [11]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array_a[-1]

array([4, 5, 6])

In [13]:
array_a[:,-1]

array([3, 6])

In [14]:
array_a[-1,-1]

6

## Assigning values in Numpy

In [15]:
array_a[0,2]=9

In [16]:
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [17]:
array_a[0]=9

In [18]:
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [19]:
array_a[:,0]=9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [20]:
list_a=[8,7,8]
array_a[0]=list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [21]:
type(array_a[0])

numpy.ndarray

In [22]:
array_a[:]=9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [23]:
array_a=9
array_a

9

In [24]:
type(array_a)

int

## Elementwise properties of Arrays

In [25]:
array_a=np.array([7,8,9])
array_a

array([7, 8, 9])

In [26]:
array_b=np.array([[1,2,3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_a+2

array([ 9, 10, 11])

In [28]:
list_a=[1,2,3]
list_a+[2]

[1, 2, 3, 2]

In [29]:
array_a + array_b[0]

array([ 8, 10, 12])

## Types of Data supported by Numpy

In [30]:
array_a=np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
array_a=np.array([[1,2,3],[4,5,6]], dtype="float32")
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [32]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [33]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [34]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.bool)
array_a

<ipython-input-34-567432d56e46>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a=np.array([[1,2,3],[4,5,6]], dtype=np.bool)


array([[ True,  True,  True],
       [ True,  True,  True]])

In [35]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=bool)
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [36]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=np.str)
array_a

<ipython-input-36-fb3f2b458729>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_a=np.array([[1,2,3],[4,5,6]], dtype=np.str)


array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [37]:
array_a=np.array([[1,2,3],[4,5,6]], dtype=str)
array_a

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [38]:
array_a=np.array([[10,2,3],[4,5,6]], dtype=str)
array_a

array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

# Characteristics of Numpy functions

## Broadcasting

In [39]:
array_a=np.array([1,2,3])
array_a

array([1, 2, 3])

In [40]:
array_b=np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [41]:
matrix_c=np.array([[1,2,3],[4,5,6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.add(array_b,matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

## Type casting

In [45]:
np.add(array_b,matrix_c,dtype=np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [46]:
np.mean(matrix_c,axis=0)

array([2.5, 3.5, 4.5])

In [47]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.mean(matrix_c,axis=1)

array([2., 5.])

# Numpy Datatypes

## ndarrays

In [50]:
import numpy as np

In [51]:
array_a = np.array([1,2,3])
print(array_a)

[1 2 3]


In [52]:
type(array_a)

numpy.ndarray

In [53]:
array_a.shape

(3,)

In [54]:
array_b=np.array([[7,8,9],[10,11,12]])

In [55]:
type(array_b)

numpy.ndarray

In [56]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [57]:
array_b.shape

(2, 3)

In [58]:
array_b.shape[0]

2

In [59]:
array_b.shape[1]

3

In [60]:
array_c=np.array(13)

In [61]:
type(array_c)

numpy.ndarray

In [62]:
print(array_c)

13


In [63]:
array_c.shape

()

In [64]:
array_d=np.array([15])

In [65]:
type(array_d)

numpy.ndarray

In [66]:
print(array_d)

[15]


In [67]:
array_d.shape

(1,)

In [68]:
array_e=np.array([[15]])
array_e

array([[15]])

## List vs Arrays

In [70]:
list_a=[[1,2,3],[4,5,6]]

In [71]:
len(list_a)

2

In [72]:
array_a=np.array(list_a)

In [73]:
type(list_a)

list

In [74]:
type(array_a)

numpy.ndarray

In [75]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [76]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [77]:
array_a.shape

(2, 3)

In [78]:
list_a.shape #wrong statement

AttributeError: 'list' object has no attribute 'shape'

In [79]:
len(list_a)

2

In [80]:
len(list_a[0])

3

In [81]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [82]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [83]:
list_b=list_a[0]+list_a[1]

In [84]:
array_b=array_a[0]+array_a[1]

In [85]:
print(list_b)

[1, 2, 3, 4, 5, 6]


In [86]:
print(array_b)

[5 7 9]


In [87]:
import math

In [88]:
array_e=math.sqrt(list_a)
print(array_e)

TypeError: must be real number, not list

In [89]:
array_e=math.sqrt(list_a[1,0])
print(array_e)

TypeError: list indices must be integers or slices, not tuple

In [90]:
array_e=math.sqrt(array_a[1,0])
print(array_e)

2.0


In [91]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])