In [1]:
import numpy as np

## np.mean()

In [2]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])

In [3]:
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [4]:
np.mean(matrix_A)

3.4

In [5]:
np.mean(matrix_A[0])

1.0

In [6]:
np.mean(matrix_A[:,0])

2.6666666666666665

In [7]:
np.mean(matrix_A,axis=0)

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [8]:
np.mean(matrix_A,axis=1)

array([1. , 5.2, 4. ])

In [9]:
np.sqrt(matrix_A)

array([[1.        , 0.        , 0.        , 1.73205081, 1.        ],
       [1.73205081, 2.44948974, 2.44948974, 1.41421356, 3.        ],
       [2.        , 2.23606798, 1.73205081, 2.82842712, 0.        ]])

In [10]:
matrix_A.sqrt() # wrong statement

AttributeError: 'numpy.ndarray' object has no attribute 'sqrt'

In [11]:
np.mean(matrix_A,axis=1,dtype=np.int64)

array([1, 5, 4])

## Min & Max values

In [12]:
import numpy as np

In [13]:
np.min(matrix_A)

0

In [14]:
np.amin(matrix_A)

0

In [15]:
np.minimum(matrix_A[0],matrix_A[2])

array([1, 0, 0, 3, 0])

In [16]:
np.minimum.reduce(matrix_A)

array([1, 0, 0, 2, 0])

In [17]:
np.min(matrix_A,axis=0)

array([1, 0, 0, 2, 0])

In [18]:
np.max(matrix_A)

9

In [19]:
np.amax(matrix_A)

9

In [20]:
np.maximum.reduce(matrix_A)

array([4, 6, 6, 8, 9])

# Statistical order functions

In [21]:
import numpy as np

In [22]:
matrix_A=np.array([[1,0,0,3,1],[3,6,6,2,9],[4,5,3,8,0]])
matrix_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

## np.ptp()

In [23]:
np.ptp(matrix_A)

9

In [24]:
np.ptp(matrix_A, axis=0)

array([3, 6, 6, 6, 9])

In [25]:
np.ptp(matrix_A, axis=1)

array([3, 7, 8])

## np.percentile()

In [26]:
np.sort(matrix_A,axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [27]:
np.percentile(matrix_A,70)

4.799999999999999

In [28]:
np.percentile(matrix_A,70, interpolation="midpoint")

4.5

In [30]:
np.percentile(matrix_A,70, interpolation="lower")

4

In [31]:
np.percentile(matrix_A,70, interpolation="nearest")

5

In [32]:
type(np.percentile(matrix_A,70))

numpy.float64

In [33]:
type(np.percentile(matrix_A,70, interpolation="lower"))

numpy.int64

## np.quantile()

In [34]:
np.quantile(matrix_A, 0.70)

4.799999999999999

In [36]:
np.quantile(matrix_A, 0.70, interpolation="nearest")

5

In [37]:
np.quantile(matrix_A, 0.70, interpolation="lower")

4

In [38]:
np.quantile(matrix_A, 0.70, interpolation="midpoint")

4.5